import { CypressReportSuite } from '../../../types'

const singleSuiteWithPendingTests: CypressReportSuite = {
  uuid: '',
  title: '',
  fullFile: '',
  file: '',
  beforeHooks: [],
  afterHooks: [],
  tests: [],
  passes: [],
  failures: [],
  pending: [],
  skipped: [],
  duration: 0,
  root: true,
  rootEmpty: true,
  _timeout: 2000,
  suites: [
    {
      uuid: '8cdd344e-3225-4b1c-a7b1-37df014debd7',
      title: 'verify sth [123]',
      fullFile: '',
      file: '',
      beforeHooks: [],
      afterHooks: [],
      tests: [
        {
          title: 'successfully verifies sth',
          fullTitle: 'verify sth [123] successfully verifies sth',
          timedOut: null,
          duration: 0,
          state: 'pending',
          speed: null,
          pass: false,
          fail: false,
          pending: true,
          context: null,
          code: '',
          err: {},
          uuid: '36347f33-e270-4f02-91e8-a916043c62aa',
          parentUUID: '8cdd344e-3225-4b1c-a7b1-37df014debd7',
          isHook: false,
          skipped: false,
        },
        {
          title: 'successfully verifies sth else',
          fullTitle: 'verify sth [123] successfully verifies sth else',
          timedOut: null,
          duration: 0,
          state: 'pending',
          speed: null,
          pass: false,
          fail: false,
          pending: true,
          context: null,
          code: '',
          err: {},
          uuid: '207d203c-c137-43f2-b4b5-d56da9b94517',
          parentUUID: '8cdd344e-3225-4b1c-a7b1-37df014debd7',
          isHook: false,
          skipped: false,
        },
      ],
      suites: [],
      passes: [],
      failures: [],
      pending: [
        '36347f33-e270-4f02-91e8-a916043c62aa',
        '207d203c-c137-43f2-b4b5-d56da9b94517',
      ],
      skipped: [],
      duration: 0,
      root: false,
      rootEmpty: false,
      _timeout: 2000,
    },
  ],
}

export default singleSuiteWithPendingTests
